### ISSUE TITLE
Call CheckTxRouter method twice

### ISSUE THREAD

**Issue by saguywalker** [ndidplatform/smart-contract#19]
CheckTxRouter method is called in both [CheckTx](https://github.com/ndidplatform/smart-contract/blob/master/abci/app/v1/app.go#L294) and [DeliverTxRouter](https://github.com/ndidplatform/smart-contract/blob/master/abci/app/v1/deliverTx.go#L93) methods.
Is it necessary to call it twice?

**Comment by re7eal** [comment]
Yes, it is necessary as stated in Tendermint documentation (https://tendermint.com/docs/spec/abci/abci.html). CheckTx executes part of the transaction processing logic while DeliverTx executes in full.
